name: Build Application

on:
  push:
    branches:
      - main

concurrency:
  group: sociable-weaver-app
  cancel-in-progress: false

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Application
        run: ./gradlew build
